redis:
  image: redis
  ports:
   - "6379:6379"
db:
  image: mariadb
  ports:
   - "3306:3306"
  environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rbm2m
      MYSQL_USER: rbm2m
      MYSQL_PASSWORD: rbm2m
